services:
  nostr-relay:
    image: ghcr.io/dockur/strfry:latest
    container_name: nostling-dev-relay
    ports:
      - "8080:8080"
    volumes:
      - ./strfry.conf:/etc/strfry.conf:ro
      - strfry-data:/app/strfry-db

volumes:
  strfry-data:
